import React,{useEffect,useState} from 'react';
import { AlertTriangle, Clock3, Loader2, Plus } from 'lucide-react';
import { managementService } from '../../services/managementService';
import { useAuth } from '../../hooks/useAuth';
import type { LawFirm, LawFirmInteraction } from '../../types/database';

export function ProcessLawFirmTab({processId,canEdit}:{processId:string;canEdit:boolean}){
 const {profile}=useAuth(); const canManageFirms = profile?.role === 'ADMIN' || profile?.role === 'GESTOR'; const [firms,setFirms]=useState<LawFirm[]>([]); const [interactions,setInteractions]=useState<LawFirmInteraction[]>([]); const [mgmt,setMgmt]=useState<any>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
 const [firmId,setFirmId]=useState(''); const [lawyerName,setLawyerName]=useState(''); const [lawyerEmail,setLawyerEmail]=useState(''); const [newFirmName,setNewFirmName]=useState('');
 const [type,setType]=useState('ENVIO'); const [subject,setSubject]=useState(''); const [summary,setSummary]=useState(''); const [expected,setExpected]=useState('');
 const load=async()=>{setLoading(true);const [f,i,m]=await Promise.all([managementService.listLawFirms(),managementService.listLawFirmInteractions(processId),managementService.getProcessManagement(processId)]);setFirms(f.data);setInteractions(i.data);setMgmt(m.data);setError(f.error||i.error||m.error);if(m.data){setFirmId(m.data.law_firm_id||'');setLawyerName(m.data.lawyer_name||'');setLawyerEmail(m.data.lawyer_email||'');}setLoading(false)};
 useEffect(()=>{load()},[processId]);
 const createFirm=async()=>{if(newFirmName.trim().length<2)return;const r=await managementService.createLawFirm({nome:newFirmName.trim(),active:true});if(r.error){setError(r.error);return;}setNewFirmName('');if(r.data)setFirmId(r.data.id);load();};
 const assign=async()=>{const r=await managementService.updateProcessManagement(processId,{law_firm_id:firmId||null,lawyer_name:lawyerName.trim()||null,lawyer_email:lawyerEmail.trim()||null});if(r.error){setError(r.error);return;}load();};
 const add=async()=>{const r=await managementService.createLawFirmInteraction({process_id:processId,law_firm_id:firmId||null,interaction_type:type,expected_return_at:type==='ENVIO'&&expected?new Date(expected).toISOString():null,subject:subject.trim()||null,summary:summary.trim()||null,created_by:profile?.id||null});if(r.error){setError(r.error);return;}setSubject('');setSummary('');setExpected('');load();};
 if(loading)return <div className="py-10 flex justify-center"><Loader2 className="w-5 h-5 animate-spin"/></div>;
 const hasOpenSla=Boolean(mgmt?.escritorio_retorno_esperado); const overdue=(mgmt?.escritorio_dias_atraso||0)>0;
 return <div className="space-y-4">{error&&<div className="p-3 bg-red-50 border border-red-200 rounded-lg text-xs text-red-700">{error}</div>}
  <div className="border border-slate-200 rounded-xl p-4 bg-slate-50"><div className="text-xs font-bold uppercase tracking-wider text-slate-600 mb-3">Escritório responsável</div><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><select disabled={!canEdit} value={firmId} onChange={e=>setFirmId(e.target.value)} className="border rounded-lg px-3 py-2 text-xs bg-white"><option value="">Nenhum escritório</option>{firms.map(f=><option key={f.id} value={f.id}>{f.nome}</option>)}</select><input disabled={!canEdit} value={lawyerName} onChange={e=>setLawyerName(e.target.value)} placeholder="Advogado responsável" className="border rounded-lg px-3 py-2 text-xs"/><input disabled={!canEdit} value={lawyerEmail} onChange={e=>setLawyerEmail(e.target.value)} placeholder="E-mail do advogado" className="border rounded-lg px-3 py-2 text-xs"/></div>{canEdit&&<div className="mt-3 flex flex-col md:flex-row gap-2 md:items-center md:justify-between">{canManageFirms&&<div className="flex gap-2 flex-1"><input value={newFirmName} onChange={e=>setNewFirmName(e.target.value)} placeholder="Cadastrar novo escritório" className="border rounded-lg px-3 py-2 text-xs flex-1"/><button onClick={createFirm} className="px-3 py-2 border border-slate-300 bg-white rounded-lg text-xs font-semibold">Cadastrar</button></div>}<div className="flex justify-end"><button onClick={assign} className="px-4 py-2 bg-slate-900 text-white rounded-lg text-xs font-semibold">Salvar vínculo</button></div></div>}
   {hasOpenSla&&<div className={`mt-3 rounded-lg border p-3 text-xs ${overdue?'border-red-200 bg-red-50 text-red-700':'border-amber-200 bg-amber-50 text-amber-800'}`}><div className="flex items-center gap-2 font-semibold">{overdue?<AlertTriangle className="w-4 h-4"/>:<Clock3 className="w-4 h-4"/>}{overdue?`SLA vencido há ${mgmt.escritorio_dias_atraso} dia(s)`:`Retorno esperado em ${new Date(mgmt.escritorio_retorno_esperado).toLocaleString('pt-BR')}`}</div>{mgmt?.escritorio_followups_abertos>0&&<div className="mt-1">{mgmt.escritorio_followups_abertos} cobrança(s) vinculada(s) ao envio aberto.</div>}{mgmt?.escritorio_followup_devido&&<div className="mt-1 font-semibold">Follow-up devido.</div>}</div>}
  </div>
  {canEdit&&<div className="border border-slate-200 rounded-xl p-4"><div className="text-xs font-bold uppercase tracking-wider text-slate-600 mb-3">Registrar interação</div><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><select value={type} onChange={e=>{setType(e.target.value);setExpected('')}} className="border rounded-lg px-3 py-2 text-xs"><option>ENVIO</option><option>RETORNO</option><option>COBRANCA</option><option>ORIENTACAO</option><option>OUTRO</option></select>{type==='ENVIO'&&<div><input type="datetime-local" value={expected} onChange={e=>setExpected(e.target.value)} className="border rounded-lg px-3 py-2 text-xs w-full"/><div className="text-[10px] text-slate-500 mt-1">Se vazio, aplica o SLA padrão central de 3 dias corridos.</div></div>}<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Assunto" className="border rounded-lg px-3 py-2 text-xs md:col-span-2"/><textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Resumo da interação" rows={2} className="border rounded-lg px-3 py-2 text-xs md:col-span-2"/></div><button onClick={add} className="mt-3 px-4 py-2 bg-slate-900 text-white rounded-lg text-xs font-semibold inline-flex items-center gap-2"><Plus className="w-4 h-4"/>Registrar interação</button></div>}
  <div className="space-y-3">{interactions.length===0?<div className="text-center py-8 text-xs text-slate-500">Nenhuma interação registrada.</div>:interactions.map(i=><div key={i.id} className="border border-slate-200 rounded-xl p-4"><div className="flex justify-between gap-3"><div className="font-semibold text-sm">{i.interaction_type}{i.subject?` · ${i.subject}`:''}</div><div className="text-xs text-slate-500">{new Date(i.created_at).toLocaleString('pt-BR')}</div></div>{i.summary&&<div className="text-xs text-slate-600 mt-2">{i.summary}</div>}<div className="text-xs text-slate-500 mt-2">{i.law_firm?.nome||mgmt?.law_firm_nome||'Sem escritório'}{i.expected_return_at?` · retorno esperado ${new Date(i.expected_return_at).toLocaleString('pt-BR')}`:''}{i.response_to_interaction_id?' · vinculado ao envio original':''}</div></div>)}</div>
 </div>;
}
